name: ZZZ_TeaCraft
version: 1.1.0
main: com.zzz.ZZZ_teacraft
api-version: 1.20
description: Чайный плагин с эффектами напыханости
author: ZZZ

commands:
  teacraft:
    description: Главная команда плагина TeaCraft
    usage: /teacraft <subcommand>
    aliases: [tc, tea]

permissions:
  teacraft.admin:
    description: Права на административные команды
    default: op
  teacraft.use:
    description: Права на использование основных функций
    default: true