name: ZZZ_TeaCraft
version: '1.0'
main: com.zzz.ZZZ_teacraft
api-version: '1.20'
description: Tea cultivation and smoking plugin
author: ZZZ

commands:
  teacraft:
    description: Admin commands for TeaCraft
    usage: /<command> <give/bushinfo/setstage>
    permission: teacraft.admin

permissions:
  teacraft.admin:
    description: Allows use of admin commands
    default: op